version: '3.7'
services: 
    db:
        image: mysql:latest
        restart: always
        container_name: myphpapp-dbnv
        environment: 
            MYSQL_ROOT_PASSWORD: somepass
            MYSQL_DATABASE: somedatabase
        volumes: 
            - my-vol:/var/lib/sql
volumes: 
    my-vol:
